### ISSUE TITLE
assert failed triggered by zig formatter

### ISSUE THREAD

**Issue by 0x530c** [lassik/emacs-format-all-the-code#184] opened 2022-04-10 05:42 UTC
(define-format-all-formatter zig
  (:executable "zig")
  (:install)
  (:languages "Zig")
  (:format (format-all--buffer-easy executable "fmt" "--stdin")))

lack of :feature keyword

**Comment by lassik** [comment] 2022-04-11 19:31
Duplicate of #186. Fixed by #186.

**Closed by lassik** 2022-04-11 19:31 UTC
